name: v8-ios-x86_64

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      v8_version:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    env:
      V8_VERSION: ${{ inputs.v8_version || github.event.inputs.v8_version }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: Scripts

      - uses: actions/setup-python@v5
        if: ${{ vars.HOST_MACOS != 'true' }}
        with:
          python-version: '3.12'
          architecture: 'x64'

      # See https://v8.dev/docs/cross-compile-ios
      - name: Fetch v8
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          cd depot_tools
          gclient
          mkdir $GITHUB_WORKSPACE/v8
          cd $GITHUB_WORKSPACE/v8
          fetch --nohooks v8
          echo "target_os = ['ios']" >> .gclient
          cat .gclient
          cd v8
          git fetch origin refs/tags/${{ env.V8_VERSION }}
          git checkout FETCH_HEAD
          gclient sync -D --force --reset

      - name: Build v8 ios-x86_64
        run: |
          export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          cd $GITHUB_WORKSPACE/v8/v8
          ls -l ./build/
          python ./tools/dev/v8gen.py x64.release
          cp $GITHUB_WORKSPACE/Scripts/v8.ios_x86_64.args.gn $GITHUB_WORKSPACE/v8/v8/out.gn/x64.release/args.gn
          cat $GITHUB_WORKSPACE/v8/v8/out.gn/x64.release/args.gn
          ls -l $GITHUB_WORKSPACE/depot_tools/ninja
          ninja -C ./out.gn/x64.release v8_monolith

      - name: Upload
        if: ${{ env.ACTIONS_RUNTIME_URL != '' }}
        uses: actions/upload-artifact@v4
        with:
          path: v8/v8/out.gn/x64.release/obj/libv8_monolith.a
          name: prebuilt_v8_ios_x86_64


