name: v8-macos-arm64

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      v8_version:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    env:
      V8_VERSION: ${{ inputs.v8_version || github.event.inputs.v8_version }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: Scripts

      - uses: actions/setup-python@v5
        if: ${{ vars.HOST_MACOS != 'true' }}
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Fetch v8
        run: |
          cd $GITHUB_WORKSPACE
          pwd

          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          cd depot_tools
          gclient
          mkdir $GITHUB_WORKSPACE/v8
          cd $GITHUB_WORKSPACE/v8
          fetch --nohooks v8
          cd v8
          git fetch origin refs/tags/${{ env.V8_VERSION }}
          git checkout FETCH_HEAD
          gclient sync -D --force --reset

      - name: Build v8 arm64
        run: |
          export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          cd $GITHUB_WORKSPACE/v8/v8
          python ./tools/dev/v8gen.py arm64.release
          cp $GITHUB_WORKSPACE/Scripts/v8.macos_arm64.args.gn $GITHUB_WORKSPACE/v8/v8/out.gn/arm64.release/args.gn
          ls -l $GITHUB_WORKSPACE/depot_tools/ninja 
          ls -l $GITHUB_WORKSPACE/depot_tools/autoninja 
          ninja -C ./out.gn/arm64.release v8_monolith

      - name: Upload
        if: ${{ env.ACTIONS_RUNTIME_URL != '' }}
        uses: actions/upload-artifact@v4
        with:
          path: v8/v8/out.gn/arm64.release/obj/libv8_monolith.a
          name: prebuilt_v8_macos_arm64


