name: v8-macos

on:
  workflow_dispatch:
    inputs:
      v8_version:
        description: 'v8 version tag'
        type: string
        required: false
  workflow_call:
    inputs:
      v8_version:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        include:
          - arch: x86_64
            v8_arch: x64
            args_file: v8.macos_x86_64.args.gn
          - arch: arm64
            v8_arch: arm64
            args_file: v8.macos_arm64.args.gn
    
    env:
      V8_VERSION: ${{ inputs.v8_version || github.event.inputs.v8_version }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: Scripts

      - uses: actions/setup-python@v5
        if: ${{ vars.HOST_MACOS != 'true' }}
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Fetch v8
        run: |
          cd $GITHUB_WORKSPACE
          pwd

          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          cd depot_tools
          gclient
          mkdir $GITHUB_WORKSPACE/v8
          cd $GITHUB_WORKSPACE/v8
          fetch --nohooks --nohistory v8
          cd v8
          git fetch origin refs/tags/${{ env.V8_VERSION }}
          git checkout FETCH_HEAD
          gclient sync -D --force --reset

      - name: Build v8 ${{ matrix.arch }}
        run: |
          export PATH=$GITHUB_WORKSPACE/depot_tools:$PATH
          cd $GITHUB_WORKSPACE/v8/v8
          python ./tools/dev/v8gen.py ${{ matrix.v8_arch }}.release
          cp $GITHUB_WORKSPACE/Scripts/${{ matrix.args_file }} $GITHUB_WORKSPACE/v8/v8/out.gn/${{ matrix.v8_arch }}.release/args.gn
          ls -l $GITHUB_WORKSPACE/depot_tools/ninja 
          ls -l $GITHUB_WORKSPACE/depot_tools/autoninja 
          ninja -C ./out.gn/${{ matrix.v8_arch }}.release v8_monolith

      - name: Upload
        if: ${{ env.ACTIONS_RUNTIME_URL != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: prebuilt_v8_macos_${{ matrix.arch }}
          path: v8/v8/out.gn/${{ matrix.v8_arch }}.release/obj/libv8_monolith.a